# Generated by Django 5.1.2 on 2024-10-28 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_alter_products_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.TextField(max_length=1000),
        ),
    ]
