# Generated by Django 5.1.2 on 2024-10-29 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='categoty',
            new_name='category',
        ),
    ]
